env:
  CICD_COMMIT: ${{ github.sha }}
  CICD_EMAIL: GitHub
  CICD_EVENTNAME: ${{ github.event_name }}
  CICD_NAME: GitHub Actions
  CICD_REFNAME: ${{ github.ref_name }}
  CICD_REFTYPE: ${{ github.ref_type }}
  CICD_REPO_SLUG: jindrapetrik/jpexs-decompiler
  GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GITHUB_USER: jindrapetrik
  NIGHTLY_BRANCH: dev
jobs:
  build:
    container: debian:sid
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout
      uses: actions/checkout@v3
    - continue-on-error: true
      name: Set up JDK 1.8
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 8
    - continue-on-error: true
      name: Set up PHP
      run: 'apt update -y -qq

        apt install -y -qq php

        '
    - continue-on-error: true
      name: Set up NSis
      run: 'bash -c ''echo "deb http://ftp.debian.org/debian unstable main contrib
        non-free" >> /etc/apt/sources.list.d/unstable.list''

        apt-get -y update

        apt-get -y install -t unstable nsis

        makensis -VERSION

        '
    - continue-on-error: true
      name: Set up ant
      run: "apt install -y -qq ant \n"
    - continue-on-error: true
      name: Build
      run: 'export CICD_TEMP=${{ runner.temp }}

        chmod a+x ./cicd_scripts/*.sh

        ./cicd_scripts/before_install.sh

        ./cicd_scripts/script.sh

        '
name: build
on:
  repository_dispatch:
    types: trigger-ga___main.yml
